import { test, expect } from '@playwright/test';
import { readFileSync, existsSync } from 'fs';

const cachePath = 'test-data/.page-cache.json';
const pagesToCheck: string[] = existsSync(cachePath)
  ? JSON.parse(readFileSync(cachePath, 'utf-8'))
  : ['/'];

// Archive/taxonomy/author pages generated by WordPress may lack full SEO tags
const isArchivePage = (p: string) =>
  p.startsWith('/category/') || p.startsWith('/tag/') || p.startsWith('/author/');

test.describe('SEO Tags', () => {
  for (const pagePath of pagesToCheck) {
    const label = pagePath === '/' ? 'homepage' : pagePath;
    const isArchive = isArchivePage(pagePath);

    test(`SEO checks on ${label} @smoke`, async ({ page }) => {
      test.setTimeout(60000);
      await page.goto(pagePath, { waitUntil: 'domcontentloaded' });

      await test.step('title length 10–70 chars', async () => {
        const title = await page.title();
        if (isArchive && !title) {
          console.warn(`[SEO] Empty title on archive page ${pagePath} — fix in WordPress SEO plugin`);
          return;
        }
        expect(title, `Missing title on ${pagePath}`).toBeTruthy();
        expect(title.length, `Title too short on ${pagePath}: "${title}"`).toBeGreaterThanOrEqual(10);
        expect(title.length, `Title too long on ${pagePath}: "${title}"`).toBeLessThanOrEqual(70);
      });

      await test.step('meta description 50–160 chars', async () => {
        const desc = await page.getAttribute('meta[name="description"]', 'content');
        if (isArchive && !desc) {
          console.warn(`[SEO] Missing meta description on archive page ${pagePath}`);
          return;
        }
        expect(desc, `Missing meta description on ${pagePath}`).toBeTruthy();
        if (desc) {
          expect(desc.length, `Meta description too short on ${pagePath}`).toBeGreaterThanOrEqual(50);
          expect(desc.length, `Meta description too long on ${pagePath}`).toBeLessThanOrEqual(160);
        }
      });

      await test.step('canonical URL is absolute', async () => {
        const canonical = await page.getAttribute('link[rel="canonical"]', 'href');
        expect(canonical, `Missing canonical tag on ${pagePath}`).toBeTruthy();
        expect(canonical, `Canonical should be an absolute URL on ${pagePath}`).toMatch(/^https?:\/\//);
      });

      await test.step('Open Graph tags present', async () => {
        const ogTitle = await page.getAttribute('meta[property="og:title"]', 'content');
        const ogDesc = await page.getAttribute('meta[property="og:description"]', 'content');
        const ogImage = await page.getAttribute('meta[property="og:image"]', 'content');
        const ogUrl = await page.getAttribute('meta[property="og:url"]', 'content');
        if (isArchive) {
          // warn only — archive pages often lack full OG tags
          if (!ogTitle) console.warn(`[SEO] Missing og:title on ${pagePath}`);
          if (!ogDesc) console.warn(`[SEO] Missing og:description on ${pagePath}`);
          if (!ogImage) console.warn(`[SEO] Missing og:image on ${pagePath}`);
          if (!ogUrl) console.warn(`[SEO] Missing og:url on ${pagePath}`);
        } else {
          expect(ogTitle, `Missing og:title on ${pagePath}`).toBeTruthy();
          expect(ogDesc, `Missing og:description on ${pagePath}`).toBeTruthy();
          expect(ogImage, `Missing og:image on ${pagePath}`).toBeTruthy();
          expect(ogUrl, `Missing og:url on ${pagePath}`).toBeTruthy();
        }
      });

      await test.step('exactly one H1', async () => {
        const h1Count = await page.locator('h1').count();
        expect(h1Count, `Page ${pagePath} should have exactly one H1`).toBe(1);
      });

      await test.step('all images have alt attributes', async () => {
        const missingAlt: string[] = await page.evaluate(() =>
          [...document.querySelectorAll('img')]
            .filter(img => !img.getAttribute('alt') && img.src && !img.src.startsWith('data:'))
            .map(img => img.src)
        );
        expect(
          missingAlt,
          `Images missing alt on ${pagePath}:\n${missingAlt.join('\n')}`
        ).toHaveLength(0);
      });

      if (pagePath === '/') {
        await test.step('robots meta does not contain noindex', async () => {
          const robots = await page.getAttribute('meta[name="robots"]', 'content');
          if (robots) {
            expect(
              robots.toLowerCase(),
              `Homepage robots meta contains noindex: "${robots}"`
            ).not.toContain('noindex');
          }
        });
      }
    });
  }
});
